# Generated by Django 4.2.1 on 2023-05-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamings', '0002_alter_streamings_num_visualizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamings',
            name='num_visualizations',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='streamings',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
