# Generated by Django 4.2.1 on 2023-05-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamings', '0004_customerstreaming_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamings',
            name='num_ratings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
