# Generated by Django 4.2.1 on 2023-05-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamings', '0005_streamings_num_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamings',
            name='num_ratings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='streamings',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
